site_name: My Docs
site_url: 
site_author: JW Tsai
nav:
    - Home: index.md
    - About: about.md
    - Jupyter: Untitled1.ipynb
    
theme: readthedocs
markdown_extensions:
    - extra
    - smarty
    - toc:
        permalink: []
    - admonition
    - def_list
    - footnotes
    - tables

plugins:
  - mkdocs-jupyter
  - search
  - autolinks

  
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
